### ISSUE TITLE
There is no 'vec.col'

### ISSUE THREAD

**Issue by gh16980973** [gregr/dbKanren#1]
https://github.com/gregr/dbKanren/blob/8a39ae4d8caf4da6c9cc61fedec9fc2c6e8d9368/dbk/data.rkt#L1234

**Comment by gregr** [comment]
Thank you for catching that @halazi1 .  My tests haven't exercised this rare path through the code yet.  I also noticed that the `id=>id` remapping wasn't being applied to the newly-materialized vector.  The fix is now here: https://github.com/gregr/dbKanren/commit/81b1fc5c8764e0e45542ea825d4aa44958eb8b83

By the way @halazi1, are you making use of dbKanren in some way?  I'm interested to hear about it.

**Comment by gh16980973** [comment]
It<https://cn.bing.com/dict/search?q=It&FORM=BDVSP6&cc=cn> is<https://cn.bing.com/dict/search?q=is&FORM=BDVSP6&cc=cn> a vector<https://cn.bing.com/dict/search?q=vector&FORM=BDVSP6&cc=cn>, why<https://cn.bing.com/dict/search?q=why&FORM=BDVSP6&cc=cn> use<https://cn.bing.com/dict/search?q=use&FORM=BDVSP6&cc=cn> a hash<https://cn.bing.com/dict/search?q=hash&FORM=BDVSP6&cc=cn>-ref?. ¯\_(ツ)_/¯

PS: I'm<https://cn.bing.com/dict/search?q=I%27m&FORM=BDVSP6&cc=cn> just<https://cn.bing.com/dict/search?q=just&FORM=BDVSP6&cc=cn> doing<https://cn.bing.com/dict/search?q=doing&FORM=BDVSP6&cc=cn> some<https://cn.bing.com/dict/search?q=some&FORM=BDVSP6&cc=cn> testing<https://cn.bing.com/dict/search?q=testing&FORM=BDVSP6&cc=cn> it<https://cn.bing.com/dict/search?q=it&FORM=BDVSP6&cc=cn>, Do you know how to implement miniKanren with Idris? ^_^

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by gregr** [comment]
Thanks @halazi1 .  I haven't used Idris before, but you can implement miniKanren in a strongly-typed setting.  One example is https://github.com/JetBrains-Research/OCanren which is miniKanren implemented in OCaml.
